# Generated by Django 5.0.2 on 2024-03-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=36)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('pwd', models.CharField(max_length=10)),
                ('location', models.TextField()),
                ('service_provided', models.BooleanField(default=True)),
                ('deleted', models.BooleanField(default=False)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
    ]
