# Generated by Django 5.0.2 on 2024-03-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_db',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
