# Generated by Django 5.0.2 on 2024-03-06 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_db_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_db',
            name='unique_id',
        ),
    ]
