# Generated by Django 5.0.2 on 2024-03-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_user_db_unique_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_db',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
