# Generated by Django 5.0.2 on 2024-04-01 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_query_db'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_db',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
