# Generated by Django 5.0.2 on 2024-04-03 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_query_db_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query_db',
            name='id',
        ),
        migrations.AddField(
            model_name='query_db',
            name='query_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
