# Generated by Django 5.0.2 on 2024-04-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_query_db_query_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query_db',
            name='query_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
